// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Global struct {
	AdminIp string

	AdminPort string

	GatewayIp string

	GatewayPort string

	InnerIpPrefix []string

	AdminIpLimit []string
}

var GlobalPtr unsafe.Pointer = unsafe.Pointer(&Global{})

func CurrentGlobal() *Global {
	return (*Global)(atomic.LoadPointer(&GlobalPtr))
}

func UpdateGlobal(v *Global) {
	atomic.StorePointer(&GlobalPtr, unsafe.Pointer(v))
}
