FROM redis

RUN mkdir -p /usr/local/var/db/redis/ && chmod -R 777 /usr/local/var/db/redis/

COPY ./etc/redis.conf /usr/local/etc/redis/redis.conf

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ] 
