version: '3.7'
services:
    redis:
        container_name: pepperbus_redis
        build:
            context: .
            dockerfile: ./docker/Dockerfile.redis
    php-fpm:
        container_name: pepperbus_php-fpm
        build:
            context: .
            dockerfile: ./docker/Dockerfile.php-consumer
        volumes:
            - "${PWD}/../../pepperbus:/data/"
    golang-worker:
        container_name: pepperbus_http-worker
        build:
             context: ../
             dockerfile: ./deploy/docker/Dockerfile.golang-consumer
        ports:
            - "18080:18080"
    java-worker:
        container_name: pepperbus_java-worker
        build:
            context: ../
            dockerfile: ./deploy/docker/Dockerfile.java-consumer
        ports:
            - "18081:18081"
    pepperbus:
        container_name: pepperbus_main
        build:
            context: ../
            dockerfile: ./deploy/docker/Dockerfile.pepperbus
        ports:
            - "12017:12017"
            - "19840:19840"
        depends_on:
            - gokeeper
            - redis
            - php-fpm
            - golang-worker
            - java-worker
        command: ["-n", "pepperbus_main:19840", "-d", "pepperbus_docker", "-k", "pepperbus_gokeeper:7000"]
    gokeeper:
        container_name: pepperbus_gokeeper
        image: registry.huajiao.com/library/gokeeper:latest
        ports:
            - "7000:7000"
            - "17000:17000"
        volumes:
            - "${PWD}/../../pepperbus/deploy/etc/gokeeper/:/data/keeper/etc/"
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "pepper_bus_admin"
        command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
        ports:
            - "3306:3306"
#    dashboard-api:
#        container_name: pepperbus_dashboard_api
#        build:
#            context: ../../job-dashboard/dashboard/
#            dockerfile: ./deploy/docker/Dockerfile.dashboard-api
#        ports:
#            - "12336:12335"
#        depends_on:
#            - gokeeper
#            - mysql
#            - pepperbus
#        command: ["-p",":12335","-a","admin","-s","root:@tcp(mysql:3306)/pepper_bus_admin?charset=utf8&parseTime=True&loc=Local","-e","debug","-d","pepperbus_docker","-k","pepperbus_gokeeper:17000"]
#    dashboard-ui:
#        container_name: pepperbus_dashboard_ui
#        build:
#            context: ../../job-dashboard/dashboard-ui
#            dockerfile: ./deploy/docker/Dockerfile.dashboard-ui
#        ports:
#            - "9528:9528"
#        volumes:
#            - "${PWD}/../../job-dashboard/dashboard-ui/:/dashboard-ui"
